// apps/workspace/scripts/compile-theme.ts
import fs from 'node:fs'
import path from 'node:path'
import { ElementSeven } from '@clearline7/set-definitions'

// 1. Generate the CSS using your new method
const cssContent = `
/* AUTO-GENERATED by scripts/compile-theme.ts
  Do not edit manually. Source: @clearline7/set-definitions 
*/

@import "tailwindcss";

${ElementSeven.toTailwindCSS()}
`

// 2. Define the output path (e.g., your global CSS file)
const outputPath = path.join(process.cwd(), 'src/app/globals.css')

// 3. Write the file
fs.writeFileSync(outputPath, cssContent, 'utf-8')

console.log(`✅ Theme compiled to ${outputPath}`)
console.log(`   - Colors: ${Object.keys(ElementSeven.colors).length}`)
console.log(`   - Spacing: ${Object.keys(ElementSeven.spacing.scale).length}`)
